## project的task文件夹
dir: _DIR_ 
## task里的data存储文件夹
input: input
## task里的output存储文件夹
output: output
report: report

## 参考基因组文件夹
ref:  _ref_  ###应该有fa、fai、gtf三个文件
ref_fa:  _ref_fa_ 
ref_fai:  _ref_fai_ 
ref_gtf: _ref_gtf_ 

## 软件的安装目录
salmon:  _salmon_ 
gffread: _gffread_ 
multiqc: _multiqc_ 


## fq数据 应该按sample分好文件夹
fq: _DIR_ 
suffix_fq1: _suffix_fq1_   ## fq1后缀形式
suffix_fq2: _suffix_fq1_    ## fq2后缀形式


# 可能需要考虑的参数
thread: 12     #线程数